name: Deploy
on:
  push:
    branches:
      - source

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "Build dependencies"
        run: npm install

      - name: Deploy
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Required
