name: Deploy
on:
  push:
    branches:
      - source

jobs:
  deployments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "Build dependencies"
        run: npm install

      - name: Deploy
        run: |
          git config user.name "aceew-github"
          git config user.email "a+gh-automatic@aceew.me"
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Required
